#248 Add multi-key capture shortcut support
nvim-orgmode/orgmode pull request #253
Opened 2022-04-12 19:20 UTC by TravonteD

This adds the orgmode functionality documented
here: https://orgmode.org/manual/Template-elements.html

2022-04-12 19:25 UTC, TravonteD commented
@kristijanhusak I've run `make format`, but the format ci still fails. Anything else that I need to do?

2022-04-12 20:25 UTC, TravonteD commented
Got it, needed a stylua update

2022-04-15 10:23 UTC, kristijanhusak requested changes
Generally works ok, only that issue with the label.
I tested how Emacs does this, and basically it's same, but it has some indications that there are nested templates. Here's the gif:
![nested-template](https://user-images.githubusercontent.com/1782860/163559930-69653061-8ee7-40ad-8d76-e62515f92ad0.gif)
If you think those would be simple to add, that would be great. If it complicates it, I believe this implementation is also good enough.

2022-04-15 10:23 UTC, kristijanhusak commented on lua/orgmode/capture/init.lua
> +        label = template.description,
label is `nil` when this is a "parent" template (string).

2022-04-16 14:50 UTC, TravonteD commented
I've added the ellipses indicator for toplevel templates as well, it was straight forward to add.

2022-04-17 17:11 UTC, kristijanhusak approved these changes
Looks good, thanks!

2022-04-17 17:11 UTC, merged