Enable archiving from agenda
nvim-orgmode/orgmode pull request #354
Opened 2022-06-26 22:04 UTC by jgollenz

closes #339

Needs some more testing. Looks to me like it may archive more than intended

2022-06-27 09:47 UTC, kristijanhusak requested changes
> Looks to me like it may archive more than intended

It doesn't. It just loads the wrong state once the headline is gone. Applying the suggested change will just reload the agenda view and it should work fine.

2022-06-27 09:47 UTC, kristijanhusak commented on lua/orgmode/agenda/init.lua
> +    update_in_place = true,
```suggestion
    redo = true,
```

2022-06-27 15:17 UTC, jgollenz commented
> it should work fine
It only does when the file where the headline to be archived is located is opened. Otherwise it will e.g. archive the whole top-level parent tree of a level three headline. Need to investigate

2022-06-27 15:44 UTC, jgollenz commented
[This line](https://github.com/nvim-orgmode/orgmode/blob/07d0e00baedcbe8b4f2175f8d9fbefac2a2d38b5/lua/orgmode/org/mappings.lua#L39) returns an empty string and consequently messes with the call to `refile_file_headline_to_archive`, I think

2022-06-27 19:35 UTC, kristijanhusak commented
> It only does when the file where the headline to be archived is located is opened. Otherwise it will e.g. archive the whole top-level parent tree of a level three headline

I can't reproduce this. Once you have reproducible steps let me know so I can take a look

2022-06-29 22:51 UTC, jgollenz commented
1. create a test file: 
```lua
* foo
** bar
*** heading to archive
    <2022-06-30>
```
2. nvim -u [minimal_init.lua](https://gist.github.com/jgollenz/27cebddeb8834fe5f08ab44b3ade3bb8)
3. `<leader>oa`     -- leader is mapped to <space>
4. navigate to `heading to archive`
5. `<leader>o$`

Archiving the headline works, but at this point the whole parent tree of the headline in question is removed from the test file (leaving it empty in this case, but not necessarily). So far this always went up to the top-level parent heading

2022-07-03 21:33 UTC, jgollenz commented
@kristijanhusak maybe I'm overlooking something, but we don't have unit tests for archiving yet, correct? Should we add some?

2022-07-03 21:47 UTC, kristijanhusak commented
We don't have any. I'm always in for more tests. It was a bit tricky to add them, but if you figure out a way to do some testing around it, please do so.

2022-07-03 21:59 UTC, jgollenz commented
Alright, then let's open an issue for that and handle it separately. Not sure when I get around to it.

2022-07-09 12:02 UTC, kristijanhusak commented
Let's use `org_agenda_archive` instead of `org_agenda_archive_subtree`, to follow Emacs convention https://orgmode.org/manual/Agenda-Commands.html#:~:text=short%20%24%20(-,org%2Dagenda%2Darchive,-)

2022-07-09 13:04 UTC, jgollenz commented
> Let's use `org_agenda_archive` instead of `org_agenda_archive_subtree`

done

2022-07-09 15:10 UTC, kristijanhusak approved these changes
Looks good, thanks!

2022-07-09 15:10 UTC, merged