fix(mappings): properly get old mapping
nvim-orgmode/orgmode pull request #554
Opened 2023-05-03 10:01 UTC by danilshvalov

I played around a bit with the problem described in #553. It seems to me that the point is that we are calling the wrong `old_cr_mapping`. I replaced `vim.fn.maparg` with `vim.api.nvim_get_keymap` and the problem went away.

2023-05-03 21:04 UTC, jgollenz requested changes
Looks good to me, thank you! Just some annotations and good to merge :+1:

2023-05-03 21:04 UTC, jgollenz commented on lua/orgmode/utils/init.lua
> +---@param data KeymapData
Please add a `---@returns rhs string` annotation here

2023-05-03 21:04 UTC, jgollenz commented on lua/orgmode/config/init.lua
> +function Config:setup_mappings(category, buffer)
While we're at it, please annotate the function. Thanks!

2023-05-03 21:36 UTC, danilshvalov commented
Done

2023-05-04 05:34 UTC, jgollenz approved these changes

2023-05-04 05:35 UTC, merged

2023-05-04 05:42 UTC, kristijanhusak commented
I think we will need to expand on this a bit more. This functionality now always tries to grab the buffer level mapping, but some plugins that map <CR> actually map it globally, so we will never have an "old_mapping" here in those case.
Code should do this:
* Try to grab buffer level mapping
* If there isn't any, try to grab global level mapping

2023-05-04 20:47 UTC, kristijanhusak commented
Note that I added some additional logic around this to make sure it grabs both local and global mapping and I also moved it to store the mapping per buffer level https://github.com/nvim-orgmode/orgmode/commit/07d412eb15155c8391945a5bbbfd1caa996888bc