fix(hyperlinks): link-follow for "file:../" and "../"
nvim-orgmode/orgmode pull request #621
Opened 2023-10-22 10:38 UTC by seflue

Following a relative link starting with "../" is now supported.

Examples:
file:../somedir/some.org
../somedir/some.org

Previous it was possible to follow the first link, but a file "false" got opened instead of the target file. The second type was unsupported.

Because autocompletion works, it was easy for the user to create such links and surprising, that they didn't work.

2023-10-22 11:08 UTC, kristijanhusak requested changes
Looks good! Can we just add a test to url_spec for this case?

2023-10-22 13:49 UTC, seflue commented
> Looks good! Can we just add a test to url_spec for this case?

Done.

2023-10-23 09:16 UTC, kristijanhusak approved these changes

2023-10-23 09:16 UTC, merged

2023-10-23 09:16 UTC, kristijanhusak commented
Thanks!