Feature/allow configuring keymap descriptions
nvim-orgmode/orgmode pull request #789
Opened 2024-08-03 07:35 UTC by snoblenet

Allows the optional configuration of a keymap's `desc` alongside its `lhs`.

Related issues:

https://github.com/nvim-orgmode/orgmode/issues/788
https://github.com/nvim-orgmode/orgmode/issues/781

2024-08-12 12:53 UTC, kristijanhusak requested changes
Thanks for the PR! It looks great, just one small nit and it's good to go!

2024-08-12 12:53 UTC, kristijanhusak commented on lua/orgmode/config/mappings/map_entry.lua
> +  end
We can remove some nesting here.


```suggestion
  if type(user_mapping) == 'table' and user_mapping.desc then
    map_opts.desc = user_mapping.desc
  end
```

2024-08-15 00:16 UTC, snoblenet commented
> Thanks for the PR! It looks great, just one small nit and it's good to go!

Cheers. I'm pretty sure I've now applied your requested change and merged in the latest master...?

2024-08-15 08:33 UTC, kristijanhusak approved these changes
Looks good, thanks!

2024-08-15 08:33 UTC, merged