Decapitalize keywords in completion, add syntax highlighting for decapitalized blocks
nvim-orgmode/orgmode pull request #89
Opened 2021-09-14 02:44 UTC by shaunsingh

lowercase keywords are the norm in org-mode, uppercase is just used in the manuals to make them stand out more. This changes the completion to use lowercase instead of uppercase 

TODO: Add back syntax highlighting for uppercase keywords

2021-09-14 05:31 UTC, kristijanhusak requested changes

2021-09-14 05:31 UTC, kristijanhusak commented on lua/orgmode/org/syntax.lua
> +        [[syntax region orgmodeBlockSrc%s matchgroup=comment start="^\s*#+begin_src\ %s\s*$" end="^\s*#+END_SRC\s*$" keepend contains=@orgmodeBlockSrc%s,org_block_delimiter]],
You missed end src here

2021-09-14 06:45 UTC, kristijanhusak commented
Is there any specific documentation about this? I know lowercase also works, but I didn't knew it was norm. I don't see why all of the manual would use uppercase as an example if it's not norm?

Also, general issue with this is that we should preserve both uppercase and lowercase for certain functionality (highlighting), which current change doesn't cover.

2021-09-15 17:21 UTC, kristijanhusak commented
You can update all syntax matches to start with `\c`, that will make it case insensitive.

2022-04-23 12:55 UTC, TravonteD commented
@kristijanhusak this pr can be closed

2022-04-23 15:19 UTC, closed without merging